### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by SunlightBro** [marcglasberg/async_redux#95]
### I opened this issue to keep track of all dependencies, so that [async_redux](https://github.com/marcglasberg/async_redux/) can migrate to null-safety.

```
Computing null safety support...
Package Name                Current  Upgradable  Resolvable  Latest

direct dependencies:
fast_immutable_collections  ✗1.0.28  ✗1.0.28     ✗1.0.28     ✗1.0.28
weak_map                    ✗1.3.1   ✗1.3.1      ✗1.3.1      ✗1.3.1

dev_dependencies: all support null safety.
```

- weak_map is done 😉, just needs to be published to pub.dev
- fast_immutable_collections

Overall this would be the dependencies  in the `pubspec.yaml`:
```
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  logging: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.0-nullsafety
  file: ^6.0.0
  weak_map: ^1.3.1 # => ^1.4.0-nullsafety
  fast_immutable_collections: ^1.0.28 # => ^1.1.0-nullsafety
  meta: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.2
  async: ^2.5.0
  flutter_test:
    sdk: flutter
```
